name: Scheduled health check

on:
  ##schedule:
    ##- cron:  '0 0 * * *'
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  healthcheck:
    runs-on: ubuntu-20.04
    steps:
      - name: Check the deployed service URL
        uses: jtalk/url-health-check-action@v4
        with:
          url: https://full-stack-open-pokedex-c3jl.onrender.com
          follow-redirect: false
          max-attempts: 3
          retry-delay: 10s
          retry-all: false